# Generated by Django 5.0.7 on 2024-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_mainpageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='experience')),
            ],
        ),
    ]
